import RPi.GPIO as GPIO

# NOTE: USE THIS METHOD WHEN CATCHING ERRORS OR EXCEPTIONS
# IT SHUTS EVERYTHING DOWN

FAN_IN1_PIN = 21
FAN_IN2_PIN = 20
FAN_IN3_PIN = 16
PUMP_IN1_PIN = 12
DAMPER_IN1_PIN = 24
DAMPER_IN2_PIN = 23
COMPRESSOR_IN1_PIN = 15
COMPRESSOR_IN2_PIN = 14

relayPinList = [FAN_IN1_PIN, FAN_IN2_PIN, FAN_IN3_PIN, PUMP_IN1_PIN, DAMPER_IN1_PIN, DAMPER_IN2_PIN, COMPRESSOR_IN1_PIN, COMPRESSOR_IN2_PIN]

for i in relayPinList:
    GPIO.setup(i, GPIO.OUT)
    GPIO.output(i, GPIO.HIGH)


def shutdown():
    for i in relayPinList:
        GPIO.output(i, GPIO.HIGH)
    print("Shutting down")
    return 0
